#!/bin/sh
# sync-web-assets.sh: copies the single-source-of-truth web app files
# (index.html, style.css, js/) into www/, Capacitor's webDir. Plain file
# copy, no transformation/bundling - www/ is a disposable, gitignored build
# artifact regenerated by this script, never edited directly. Run before
# `npx cap sync`/`npx cap run` (or just run `npm run sync` which does both).
set -e
cd "$(dirname "$0")/.."
rm -rf www
mkdir -p www
cp index.html www/index.html
cp style.css www/style.css
cp -R js www/js
echo "Synced index.html, style.css, js/ into www/"
