#!/bin/sh
# sync-web-assets.sh: copies the single-source-of-truth web app files
# (index.html, style.css, js/, and the parts of vendor/ the native build
# actually needs) into www/, Capacitor's webDir. Plain file copy, no
# transformation/bundling - www/ is a disposable, gitignored build artifact
# regenerated by this script, never edited directly. Run before
# `npx cap sync`/`npx cap run` (or just run `npm run sync:ios` which does both).
set -e
cd "$(dirname "$0")/.."
rm -rf www
mkdir -p www
cp index.html www/index.html
cp style.css www/style.css
cp -R js www/js

# vendor/tesseract is ~11 MB, and the native build uses almost none of it:
# recognition on iOS is ML Kit (js/recognize.js dispatches there unconditionally
# on a native platform and never falls back), so the wasm cores and the 2.9 MB
# language file would be pure dead weight in the App Store binary.
#
# tesseract.min.js itself IS copied, and has to be: index.html loads it in a
# plain <script> tag that would otherwise 404 in the WKWebView. At 67 KB that's
# a fair price for keeping one index.html for both builds.
#
# If a Tesseract fallback is ever added to the native path, this is the line
# that has to change - copy the whole vendor/tesseract tree instead, and expect
# the binary to grow by ~11 MB.
mkdir -p www/vendor/tesseract
cp vendor/tesseract/tesseract.min.js www/vendor/tesseract/tesseract.min.js
cp vendor/tesseract/tesseract.min.js.LICENSE.txt www/vendor/tesseract/tesseract.min.js.LICENSE.txt

echo "Synced index.html, style.css, js/ and vendor/tesseract/tesseract.min.js into www/"
